name: Deploy Preview

permissions: {}

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-preview:
    uses: ./.github/workflows/_deploy-preview.yml
    permissions:
      contents: read
      pull-requests: write
    with:
      pr-number: ${{ github.event.pull_request.number }}
      sha: ${{ github.event.pull_request.head.sha }}
    secrets:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      DOTENV_PRIVATE_KEY: ${{ secrets.DOTENV_PRIVATE_KEY }}
